services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "lol"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "todo"
    ports:
      - "5432:5432"
